-- V1: Initial schema for LibroTech catalog

CREATE TABLE editorials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    founded_in INTEGER
);

CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    author VARCHAR(100) NOT NULL,
    isbn VARCHAR(20) UNIQUE,
    publication_date DATE NOT NULL,
    price DOUBLE PRECISION,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    editorial_id BIGINT NOT NULL,
    CONSTRAINT fk_books_editorial
        FOREIGN KEY (editorial_id)
        REFERENCES editorials(id)
);
